apiVersion: v1
kind: Service
metadata:
  name: basicdata-srv
spec:
  type: NodePort
  selector:
    app: basicdatawebapi
  ports:
    - name: basicdatawebapi
      protocol:  TCP
      port: 80
      targetPort: 80
      nodePort: 30001
    - name: basicdatawebapigrpc
      protocol:  TCP
      port: 666
      targetPort: 666
      nodePort: 30002
