apiVersion: v1
kind: Service
metadata:
  name: reports-srv
spec:
  type: NodePort
  selector:
    app: reportswebapi
  ports:
    - name: reportswebapi
      protocol:  TCP
      port: 80
      targetPort: 80
      nodePort: 30005
    - name: reportswebapigrpc
      protocol:  TCP
      port: 666
      targetPort: 666
      nodePort: 30006
