apiVersion: v1
kind: Service
metadata:
  name: identityadmin-srv
spec:
  type: NodePort
  selector:
    app: identityadmin
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32006
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
    nodePort: 32007
