apiVersion: v1
kind: Service
metadata:
  name: identityadminapi-srv
spec:
  type: NodePort
  selector:
    app: identityadminapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32004
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
    nodePort: 32005
   
